### ISSUE TITLE
Add support for namespace-based routes

### ISSUE THREAD

**Issue by hanishassim** [codingyu/laravel-goto-view#11]
Currently there's issue when there are 2 controllers of the same name, only to be differentiated by the path of the contorller's location.

for example, in my case:

```
Route::group(['namespace' => 'Web'], function () 
{
    Route::get('/', 'HomeController@index');
});
```

When there is namespace in the route, it will ignore it and navigate to HomeController located in the `\app\Http\Controllers\HomeController.php `as opposed to the correct loaction at `\app\Http\Controllers\Web\HomeController.php`

**Comment by ctf0** [comment]
this will never work because the package simply check for the text between quotes, also this will never work unless that is some sort of an external process the resolve the controller full name space.

the other reason this is hard to do is what if you have multiple namespaces ex.

```php
Route::group(['namespace' => 'Admin'], function () 
{
    // ...
    
    Route::group(['namespace' => 'Web'], function () 
    {
        Route::get('/', 'HomeController@index');
    });
});
```

**Comment by gauravmak** [comment]
I needed this to work in almost all of my projects and developed an extension for it - https://marketplace.visualstudio.com/items?itemName=freshbitsweb.laravel-traveller

**Comment by msadeghyan1996** [comment]
hey @gauravmak 
thank's , it's worked fine.
