### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by CR-FH** [codingyu/laravel-goto-view#12]
[codingyu.laravel-goto-view-unresponsive.cpuprofile.txt]
- Issue Type: `Performance`
- Extension Name: `laravel-goto-view`
- Extension Version: `1.2.3`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/username/codingyu.laravel-goto-view-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

(https://github.com/codingyu/laravel-goto-view/files/2869684/codingyu.laravel-goto-view-unresponsive.cpuprofile.txt)

**Comment by codingyu** [comment]
Thank you for using, welcome to try the new version.
