### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rdgajera** [codingyu/laravel-goto-view#13]
- Issue Type: `Performance`
- Extension Name: `laravel-goto-view`
- Extension Version: `1.2.3`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/rubingajera/codingyu.laravel-goto-view-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by codingyu** [comment]
[https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions)

**Comment by codingyu** [comment]
Thank you for using, welcome to try the new version.

**Comment by rdgajera** [comment]
Thanks
