### ISSUE TITLE
Not detecting/working on Laravel Modules package

### ISSUE THREAD

**Issue by anburocky3** [codingyu/laravel-goto-view#15]
I'm recently working on Laravel modules package. i noticed the file is no longer detected and clickable not appearing on `web.php` route file and even on ` return view("site::pages/about");` its not highlighting and not clickable.

A proper documentation would help in handy. :+1:

**Comment by codingyu** [comment]
If your module name is `Site`, you don't need to do extra configuration.
If not.
```
"laravel_goto_view.folders": {
    "default": "/resources/views",
    "site": "Modules/Site/resources/views",
},
```

**Comment by anburocky3** [comment]
What if I had multiple modules? I can add an new array just like site?

**For example:**
`"laravel_goto_view.folders": {
    "default": "/resources/views",
    "site": "Modules/Site/resources/views",
    "admin": "Modules/Admin/resources/views",
},` 
Would be better?

**Comment by codingyu** [comment]
@anburocky3 No, if you haven't defined the view path, it will work by default, and you don't need to change the configuration.
like:
```
Module name: Aaa   -> aaa::page.test      =     Modules/Aaa/resources/views/page/test.blade.php
```

**Comment by codingyu** [comment]
@anburocky3  
```
//return view("site::pages/about"); 
return view("site::pages.about");  
```
`/` replace it with `.`
Is that OK?
