### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bektasyildiz** [codingyu/laravel-goto-view#16]
- Issue Type: `Performance`
- Extension Name: `laravel-goto-view`
- Extension Version: `1.2.3`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\STAR\codingyu.laravel-goto-view-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by codingyu** [comment]
Thank you for using, welcome to try the new version.
