### ISSUE TITLE
stopped working after latest update

### ISSUE THREAD

**Issue by ctf0** [codingyu/laravel-goto-view#17]
now the view path is no longer clickable :cry: 

**update**
found the problem, its related to the new regex which in case u were using a helper method that u can pass to it the view file path then it wont work as the new regex expect the word `view` to be present in order for the ext to work correctly.

**Comment by codingyu** [comment]
Yes, this extension is not intelligent, the regular update is to reduce the number of matches, I plan to use the language server to rewrite this extension.
Regarding your question, how about if I use the regex as a configuration option and you are free to configure the rules?

**Comment by ctf0** [comment]
> how about if I use the regex as a configuration option and you are free to configure the rules?

i think that would be an awesome choice, which i think would also remove the need for 
https://github.com/codingyu/laravel-goto-view/blob/d621ab0b133fdd9acd27837dbe1e1bf745afffee/src/util.ts#L54-L63
