### ISSUE TITLE
Doesn't work when using blade syntax highlighting

### ISSUE THREAD

**Issue by DanJFletcher** [codingyu/laravel-goto-view#2]
Great extension!

One problem I'm having with this is that I can't get use it if I'm using an extension that offers syntax highlighting for blade. I've tried all the extensions in the marketplace to see if I could get your extension to work with any of them but no luck.

For now, I have to choose between syntax highlighting in my views, or the ability to `cmd`+`click` through them.

**Comment by codingyu** [comment]
Thanks, I'm trying to do some configuration to exclude or add some files or languages

**Comment by codingyu** [comment]
Support for `blade` has been added.

**Comment by DanJFletcher** [comment]
That's awesome! Thanks :D
