### ISSUE TITLE
vendor views arent clickable

### ISSUE THREAD

**Issue by ctf0** [codingyu/laravel-goto-view#20]

**Comment by codingyu** [comment]
My fault, it will be fixed at night.

**Comment by codingyu** [comment]
@ctf0  What is the specific way of writing?


```php
==========
resources
--view
----vendor
------aaa
---------a.blade.php
------bbb.blade.php
===========

view('aaa::a')  or view('bbb') ???
```

**Comment by ctf0** [comment]
`view('aaa::a')`

**Comment by codingyu** [comment]
@ctf0  I have an idea to use php to make a language server and call laravel's built-in methods to get the view or any other path.
