### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by orblazer** [codingyu/laravel-goto-view#28]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _Laravel goto view_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional info:

- This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by codingyu** [comment]
@orblazer
I published this extension in open-vsx([https://open-vsx.org/extension/codingyu/laravel-goto-view](https://open-vsx.org/extension/codingyu/laravel-goto-view)), but I did not test it (vscodium cannot coexist with vscode?).
You can install and test, if you have any questions, please feedback here.

Thanks

**Comment by orblazer** [comment]
Ok thanks, this is work. and vscodium have choose to use open-vsx for legal reason.
