### ISSUE TITLE
Add support for multiple folder

### ISSUE THREAD

**Issue by MehediDracula** [codingyu/laravel-goto-view#3]
First of all, this extension is awesome

I would like to suggest you something. one of in my project i have multiple views root folder. This extension is not working there as it's only searching inside laravel's default 'resources/views' folder.

it would be great if i can add an array of locations in settings.

**Comment by codingyu** [comment]
Support for multiple folder has been added.

**Comment by MehediDracula** [comment]
Thanks for this

another thing i would like to suggest. since on laravel we can add namespaced views like below. it will be also a good idea to add support for namespaced views

```php
View::addNamespace('theme', '/path/to/thwmes/views');

return view('theme::view.name');
```

**Comment by codingyu** [comment]
Ah but this may depend on where the namespace definition, I will try to achieve this function, thanks

**Comment by ctf0** [comment]
@codingyu it is possible for now to add this functionality ? so it works with the vendor views too

so calling `Abc::x` would open `views/vendor/Abc/x.blade.php`

**Comment by MehediDracula** [comment]
@codingyu since vscode has per workspace based settings maybe this extension can leverage that. maybe we can define settings in workspace settings file like below

```json
{
	"theme": "/path/to/themes/views"
}
```

**Comment by codingyu** [comment]
@ctf0  @MehediDracula  
Do you like this way?
![203821](https://user-images.githubusercontent.com/20354841/35566946-264a2cac-05fe-11e8-942f-4f9a3ddd1e43.png)
![203902](https://user-images.githubusercontent.com/20354841/35566947-2688e262-05fe-11e8-9902-156d4e7d1167.png)
![204132](https://user-images.githubusercontent.com/20354841/35566949-26c3352a-05fe-11e8-8de4-35674d986aa3.png)

**Comment by MehediDracula** [comment]
that looks amazing :fire: :fire:

**Comment by ctf0** [comment]
@codingyu many thanx for the awesome job, but one question, does the settings image means that the user have to pre populate all the possible paths beforehand for the package to work correctly ?

if so then it defines the purpose, cuz this is suppose to be done internally ex.
- get all the text between quotes
- check if it have `::` if so then get the first word b4 the `::` and search under `views/vendor/the-first-word`
- if no then search under `views/` excluding the `vendor` directory

**Comment by MehediDracula** [comment]
@ctf0 I don't think it would be ideal as your views can be anywhere. if this extension only searches on `resources/views` folder then it can't be configured.

currently, I'm working on a modular project where each module's view is under `Modules/{ModuleName}/Resources/views` folder. so, I think using settings is flexible here.

**Comment by ctf0** [comment]
@MehediDracula your example is not the default for the most, however to keep it flexible the `resources/views` should be the default for the settings, unless you added an extra path like yours

**Comment by codingyu** [comment]
@ctf0 Thank you for your advice. The next version will try this function. ☺️
