### ISSUE TITLE
Any way to configure the keyboard shortcut?

### ISSUE THREAD

**Issue by Blum** [codingyu/laravel-goto-view#31]
Is there any way to set some other shortcut to execute go-to-view? I'm using Ctrl+click and Alt+click already..
Thanks

**Comment by ashokbaruaakas** [comment]
You can add shortcut for open link.. and its working for me.. 
```
{
    "key": "alt+g",
    "command": "editor.action.openLink"
  },
```

**Comment by Blum** [comment]
Thanks :+1:
