### ISSUE TITLE
Add support for markdown in mailables.

### ISSUE THREAD

**Issue by JrBoc** [codingyu/laravel-goto-view#38]
markdown is just the function view in a controller. it calls the blade file.

![image](https://user-images.githubusercontent.com/41932859/105621179-d25a0e80-5e3f-11eb-8224-7d95fea76cfe.png)

**Comment by macbookandrew** [comment]
Change the `laravel_goto_view.regex` config to this and it will work:

```
(?<=view\(['"]|markdown\(['"]|\(view:.['"]|View::make\(['"]|@include\(['"]|@extends\(['"]|@component\(['"]|Inertia::render\(['"]|\(component:.['"]|\<)(\<x-|\<livewire:|[^'" \/>]+)
```
