### ISSUE TITLE
Laravel goto view does not work

### ISSUE THREAD

**Issue by chepevic** [codingyu/laravel-goto-view#39]
Hello,

I have installed Laravel goto view but it does not work on my laptop. I got macOS High Sierra.

In my settings.json i have

"laravel_goto_view.folders": {       
        "default": "/resources/views",
        "js": "/resources/js/Pages",
        "vendor": "/resources/views/vendor"
    },
    "laravel_goto_view.extensions": [
        ".blade.php",
        ".inky.php"
    ],  

Thanks in advance

**Comment by codingyu** [comment]
I tested the same configuration and it can run. I'm not sure what's going on in your side
