### ISSUE TITLE
Proposed to increase the controller goto function

### ISSUE THREAD

**Issue by tiansin** [codingyu/laravel-goto-view#4]
Proposal to add this function, can be used together

**Comment by codingyu** [comment]
https://github.com/stef-k/laravel-goto-controller

**Comment by tiansin** [comment]
@codingyu 
Yes, I have mentioned a issue, but he looks very busy and help wanted.

**Comment by codingyu** [comment]
@tiansin I will try to add this feature to his extensions. :upside_down_face:
