### ISSUE TITLE
[question] Does the folder setting support variables and/or absolute paths?

### ISSUE THREAD

**Issue by offstream** [codingyu/laravel-goto-view#40]
I'm working in a multi-root workspace and I have something like this in my workspace settings:

```json
{
    "folders": [
        {
            "name": "root",
            "path": "apps/laravel-project"
        },
        {
            "name": "inner",
            "path": "apps/laravel-project/some/inner/path"
        }
    ],
    "settings": {
        "laravel_goto_view.folders": {
            "default": "${workspaceFolder:root}/resources/views"
        }
    }
}
```

I've also tried it with an absolute path but it still can't find the path to the view.

It seems like it always defaults looking through folders relative to the current workspace folder.

**Comment by codingyu** [comment]
```
"laravel_goto_view.folders": {
            "default": "${workspaceFolder:root}/resources/views"
        }
```
It doesn't need to be set like this.

The default path is the project root directory of the currently open file.
