### ISSUE TITLE
[FEAT] : Publish the extension to the Open VSX Registry

### ISSUE THREAD

**Issue by mhkb** [codingyu/laravel-goto-view#42]
Would you be able to publish this extension to the Open VSX Registry (https://open-vsx.org/) so it's available to VS Code Compatible Editors, such as VSCodium?

**Comment by codingyu** [comment]
@mhkb  https://open-vsx.org/extension/codingyu/laravel-goto-view

**Comment by mhkb** [comment]
@codingyu thank you!
