### ISSUE TITLE
Auto complete function not working when extension is running

### ISSUE THREAD

**Issue by MBousss** [codingyu/laravel-goto-view#48]

**Comment by codingyu** [comment]
This extension does not support auto complete.
Do you want the name of the view to be auto complete?

**Comment by MBousss** [comment]
I did not mean that is has autocompletion. When the extension is running it bricks al autocomplition in vscode. I also have tried it on vscodium and same happened there.

**Comment by codingyu** [comment]
This extension adds document links and hovers.
Does vscode generate some logs?
