### ISSUE TITLE
Does not work for `@includeWhen`

### ISSUE THREAD

**Issue by ianjamieson** [codingyu/laravel-goto-view#57]
Out of the box, the regex does not work for `@includeWhen` directives.

Original regex:

```regex
(?<=view\(['"]|View::make\(['"]|@include\(['"]|@extends\(['"]|@component\(['"]|Inertia::render\(['"]|\<)(\<x-|\<livewire:|[^'" \/>]+)
```

**Comment by theChaosCoder** [comment]
`@includeWhen\([^'"]*['"]` would only catche this `@includeWhen(true, 'test')` but not this `@includeWhen(myfunction('abc'), 'test')`
