### ISSUE TITLE
bug on inertia

### ISSUE THREAD

**Issue by holiq** [codingyu/laravel-goto-view#63]
in inertia::render() can not goto component inside a folder with separator slash, like Auth/login, it still work if i use dot Auth.Login like bellow
<img width="363" alt="Screenshot_20221114_000306" src="https://user-images.githubusercontent.com/30729921/201534349-5d86b2f6-2731-4716-a597-8f32ef578d73.png">

**Comment by funkymonk91** [comment]
Hopefully this is still useful for you. I just encountered this and resolved it by updating my regex pattern to:

```json
"laravel_goto_view.regex": "(?<=view\\(['\"]|\\(view:.['\"]|View::make\\(['\"]|@include\\(['\"]|@extends\\(['\"]|@component\\(['\"]|Inertia::render\\(['\"]|\\(component:.['\"]|<)(?:x-|livewire:|[^'\"\\s/>]+(?:\\/[^'\"\\s/>]+)*)"
```

https://regexr.com/7ghkc

**Comment by holiq** [comment]
Thats work bro, let's make the pr to close this issue
