### ISSUE TITLE
Doesn't work on remote development

### ISSUE THREAD

**Issue by SpoonCart** [codingyu/laravel-goto-view#65]
### Bug Report
|    Q        |   A
|------------ | ------
| Version |   v1.3.8
| Remote OS | Ubuntu 22.04.1 LTS
| Dev OS | Windows 11 22H2

#### Summary
Does not work on remote development systems. 

#### Current behavior
If I run VSCode on my Ubuntu system I am able to get it to work. However, when I use my main system it does not. When you start VSCode on the remote development system with the package installed you can see it indexing. But when you use the ctrl + hover method, it does nothing. Also, I noticed the extensions manager in VSCode, the extension says enabled but it is grayed out.

**Comment by codingyu** [comment]
in wsl2 is ok, I'll try another way

**Comment by SpoonCart** [comment]
I was able to figure out the issue. My development setup looks at the root of my application builds in a folder called development. I have that as my workspace. Inside of there is where I build new components and etc... Now, if I rebase my workspace to each individual development folder, it works just fine. Its not a huge deal, just a little bug.

**Comment by SpoonCart** [comment]
You Rock, Yu!
