### ISSUE TITLE
Remove underline 

### ISSUE THREAD

**Issue by mossen** [codingyu/laravel-goto-view#7]
Any possibility to remove the underline?

**Comment by codingyu** [comment]
Sorry, this is the default link display, so can not cancel.
I'm considering rewriting this extension in a new way.

**Comment by codingyu** [comment]
settings.json ↓
`"laravel_goto_view.quickJump": false`

**Comment by mossen** [comment]
Would like to only remove underline, `"laravel_goto_view.quickJump": false` disables the extension.
