### ISSUE TITLE
Not working in $this->resource()

### ISSUE THREAD

**Issue by Vaysi** [codingyu/laravel-goto-view#8]
Hello And Thanks For Your Cool Ext...
When Im Trying To Go To Resource Controller The Extensions Does'nt Work . 
I Tried it out of Route Group , Without Middleware or Any Extra Methods But Still Nothing Happend .
By the Way Im Using 
**Manjaro Linux  17.1.7**
And 
**Vscode 1.25.1**
Thanks . 
![deepinscreenshot_20180719065952](https://user-images.githubusercontent.com/33804991/42918074-70196124-8b21-11e8-91a0-404560a49719.png)

**Comment by codingyu** [comment]
👉https://github.com/stef-k/laravel-goto-controller   You use this?

**Comment by Vaysi** [comment]
Yes . sorry its seems im in the wrong place to talk about this problem . sorry
